#!/bin/bash

update_repo() {
  pushd ${OPENSHIFT_DATA_DIR} >/dev/null
  [ -e git ] || mkdir git
  if [ -e git/${1} ]; then
    cd git/${1} && git pull -q
  else
    git clone -q ${2} git/${1}
  fi
  popd >/dev/null
}

update_repo bastion https://github.com/Katello/bastion.git
update_repo foreman_abrt https://github.com/theforeman/foreman_abrt
update_repo foreman_api https://github.com/theforeman/foreman_api.git
update_repo foreman_bootdisk https://github.com/theforeman/foreman_bootdisk
update_repo foreman_content https://github.com/theforeman/foreman_content
update_repo foreman_deployments https://github.com/theforeman/foreman_deployments
update_repo foreman-digitalocean https://github.com/theforeman/foreman-digitalocean
update_repo foreman_discovery https://github.com/theforeman/foreman_discovery
update_repo foreman-discovery-image https://github.com/theforeman/foreman-discovery-image
update_repo foreman-docker https://github.com/theforeman/foreman-docker
update_repo foreman-gutterball https://github.com/Katello/foreman-gutterball.git
update_repo foreman https://github.com/theforeman/foreman.git
update_repo foreman-installer https://github.com/theforeman/foreman-installer.git
update_repo foreman-one https://github.com/theforeman/foreman-one
update_repo foreman_remote_execution https://github.com/theforeman/foreman_remote_execution
update_repo foreman-rpms https://github.com/theforeman/foreman-packaging
update_repo foreman_salt https://github.com/theforeman/foreman_salt
update_repo foreman_sam https://github.com/Katello/foreman_sam.git
update_repo foreman-selinux https://github.com/theforeman/foreman-selinux
update_repo foreman_snapshot https://github.com/theforeman/foreman_snapshot
update_repo foreman-tasks https://github.com/theforeman/foreman-tasks
update_repo foreman-xen https://github.com/theforeman/foreman-xen
update_repo hammer-cli-csv https://github.com/Katello/hammer-cli-csv.git
update_repo hammer-cli-foreman-discovery https://github.com/theforeman/hammer-cli-foreman-discovery
update_repo hammer-cli-foreman https://github.com/theforeman/hammer-cli-foreman
update_repo hammer-cli-foreman-tasks https://github.com/inecas/hammer-cli-foreman-tasks.git
update_repo hammer-cli-gutterball https://github.com/Katello/hammer-cli-gutterball.git
update_repo hammer-cli https://github.com/theforeman/hammer-cli
update_repo hammer-cli-katello https://github.com/Katello/hammer-cli-katello.git
update_repo hammer-cli-sam https://github.com/Katello/hammer-cli-sam.git
update_repo kafo https://github.com/theforeman/kafo.git
update_repo katello-agent https://github.com/Katello/katello-agent.git
update_repo katello https://github.com/Katello/katello.git
update_repo katello-installer https://github.com/Katello/katello-installer.git
update_repo katello.org https://github.com/Katello/katello.org.git
update_repo ofi https://github.com/theforeman/ofi.git
update_repo puppet-concat https://github.com/theforeman/puppet-concat.git
update_repo puppet-dhcp https://github.com/theforeman/puppet-dhcp.git
update_repo puppet-dns https://github.com/theforeman/puppet-dns.git
update_repo puppet-foreman https://github.com/theforeman/puppet-foreman.git
update_repo puppet-foreman_proxy https://github.com/theforeman/puppet-foreman_proxy.git
update_repo puppet-git https://github.com/theforeman/puppet-git.git
update_repo puppet-puppet https://github.com/theforeman/puppet-puppet.git
update_repo puppet-tftp https://github.com/theforeman/puppet-tftp.git
update_repo smart_proxy_abrt https://github.com/theforeman/smart_proxy_abrt
update_repo smart_proxy_discovery https://github.com/theforeman/smart_proxy_discovery
update_repo smart_proxy_dynflow https://github.com/theforeman/smart_proxy_dynflow
update_repo smart-proxy https://github.com/theforeman/smart-proxy.git
update_repo smart_proxy_remote_execution_ssh https://github.com/theforeman/smart_proxy_remote_execution_ssh
update_repo smart_proxy_salt https://github.com/theforeman/smart_proxy_salt
update_repo stacker https://github.com/ohadlevy/stacker.git

cd ${OPENSHIFT_REPO_DIR}
script/rails runner "Repository.fetch_changesets" -e production
